### ISSUE TITLE
Releases?

### ISSUE THREAD

**Issue by srenatus** [fullstorydev/grpcui#15]
Heya! Thanks for sharing this project, I immediately fell in love 😍 

What do you think about having releases? It would simplify packaging this up with; I'd like to create a habitat package similar to the one we have for [`grpcurl`](https://bldr.habitat.sh/#/pkgs/core/grpcurl) (see also https://github.com/habitat-sh/core-plans/pull/2186).

**Comment by jhump** [comment]
It's definitely on my list of things to do. But with other projects, we've waited until we were comfortable with a v1.0 before providing release binaries. I suppose I could go ahead and make a v0.1.0 release. I'm not comfortable calling the current version 1.0 because I suspect there are bugs in it.

The amount of automated tests in here is virtually nil, so the project is quite immature at the moment. The testing done to date has largely been manual testing using the `testsvr` in this repo (which provides complex descriptors for really exercising the code that builds the UI form and builds the JSON request).

**Comment by jhump** [comment]
@srenatus, hopefully [this](https://github.com/fullstorydev/grpcui/releases/tag/v0.1.0) will do for now.

**Comment by srenatus** [comment]
@jhump thank you very much ❤️
