### ISSUE TITLE
is type google.protobuf.Value supported?

### ISSUE THREAD

**Issue by hyperyuri** [fullstorydev/grpcui#152]
I cant set the value when the field is google.protobuf.Value
![image](https://user-images.githubusercontent.com/54409166/146820010-ebf9500a-5ed6-4859-a4fd-77d85cb448cd.png)

This type is generic like interface{} or any in another languages

**Comment by jhump** [comment]
This is a bug. `grpcui` does have functionality for supporting this type, by providing a text area into which you can enter any valid JSON. The bug is that it should probably render an unset value as a disabled empty text area, so that when you click the checkbox to add a valid, it can correctly enable the text area. Another possible solution will be to have it replace the _unset_ label with the text area when you check the box.

**Comment by hyperyuri** [comment]
how can i help to solve this bug?

**Comment by hyperyuri** [comment]
I am thinking to make protobuf.Value be like protobuf.Any is it good a way to solve the problem?

**Comment by jhump** [comment]
So I now see that `google.protobuf.Struct` works correctly -- it shows _unset_ when the field is absent. And when you check the box, it replaces that label with a text area. And `google.protobuf.Value` should work _exactly_ the same -- the only difference between the two types is that `Value` can be _any_ kind of value where as `Struct` must be an object/map.

So if you are comfortable debugging JS code in the browser, you might step through things to figure out what is happening differently between `Struct` and `Value` when that box is checked.

The `unset` label comes from [here](https://github.com/fullstorydev/grpcui/blob/master/internal/resources/webform/webform.js#L1772). And the code to populate the form with a JSON text area is [here](https://github.com/fullstorydev/grpcui/blob/master/internal/resources/webform/webform.js#L1593). The code that reacts to the checkbox changing, and is supposed to swap in an element, replacing _unset_, is [here](https://github.com/fullstorydev/grpcui/blob/master/internal/resources/webform/webform.js#L728).

Lastly, in this repo in `./testing/cmd/testsvr` is a simple server with example methods that can exercise every possible type of input. So, for this case, it exposes a `DoManyThings` method whose request has a field named `wk` (which contains lots of fields for testing the form entry for well-known types, including `google.protobuf.Value`). Therein is a field named `optional_value` for testing precisely this case.

**Comment by jhump** [comment]
> I am thinking to make protobuf.Value be like protobuf.Any is it good a way to solve the problem?

No, you don't need to do that. Value already has correct support. This is just a bug somewhere in the code that handles the checkbox being checked.

**Comment by hyperyuri** [comment]
I will try to debug and find the error to send a PR with a fiz

**Comment by hyperyuri** [comment]
@jhump i found the error, but this field can't be a JSON, it can be everything, int, string, object and have no validation

**Comment by jhump** [comment]
Sorry, I do not understand your last message on this issue. It's not clear to me why `null` would be a bad default.

Also, I don't understand what you mean by: 

> this field can't be a JSON, it can be everything, int, string, object and have no validation

It definitely can be JSON -- that is, in fact, it's [format when marshaled to JSON](https://developers.google.com/protocol-buffers/docs/reference/google.protobuf#google.protobuf.Value) because it is really a model of an arbitrary JSON value as a protobuf message.

**Comment by hyperyuri** [comment]
The "null" is bringing the error, if i change null to {} or something else, it works.

What i said about JSON is because this field can't be only a JSON, it can be everything. It can't be validated always as JSON, because i can input only a "string", or an int and this values is not a valid JSON structure like "{ "value": "something"}

**Comment by jhump** [comment]
> The "null" is bringing the error, if i change null to {} or something else, it works.

Okay. Like I said on the PR you opened, I wonder if the root issue is elsewhere -- whatever code that is not correctly handling when the message is `google.protobuf.Value`.

Thinking about this a little more, I suspect the issue is that for normal messages (other than `google.protobuf.Value`), a null value indicates that the field is _not present_. However, for `google.protobuf.Value`, null really has two possible meanings: it could mean that the field is not present or it could mean that it is present and is [explicitly set to null](https://github.com/protocolbuffers/protobuf/blob/e5c570bb572bebe706d0389f2ea734a3e1a7d821/src/google/protobuf/struct.proto#L66).

So I guess this is confusing the code that decides whether the field is present or not.

To that end, `{}` is a better default/initial value IMO than the empty string.

> What i said about JSON is because this field can't be only a JSON

Not quite sure what this means. JSON supports values that are strings, booleans, numbers, nulls, lists, or objects. Which (not coincidentally) are exactly the types that `google.protobuf.Value` supports.

**Comment by hyperyuri** [comment]
Oh got it! that's it, so i will change the default to {}, it's better.

**Comment by hyperyuri** [comment]
Did you see my comment at my PR? @jhump

**Comment by hyperyuri** [comment]
Issue solve by #153
