### ISSUE TITLE
Question about JSON

### ISSUE THREAD

**Issue by idc77** [fullstorydev/grpcui#234]
When I use grpcui, it's able to receive JSON requests, forward them to my grpc server and receive a response and return JSON as well.
It that something so easy to do?
Why don't you release a standalone grpc to JSON gateway?
Or have I been living under a rock for the last few years?
I've always waited for grpc-web to be complete but it never is, yet here you have a middleware that simply constructs clients by reflection and posts and receives JSON objects. Mind blown.

How?

Can I simply add some magic package and have that functionality as well?

**Comment by jhump** [comment]
> Why don't you release a standalone grpc to JSON gateway?

So you are asking for something that just translates the protobuf binary payloads to JSON? FWIW, streaming and other gRPC protocol features such as compression would not really work well with this.

It sounds like maybe you are wanting a gRPC-web client that uses JSON, paired with a server that uses JSON. This is currently problematic because https://github.com/grpc/grpc-web uses a [JS protobuf library](https://github.com/protocolbuffers/protobuf-javascript) that does not support JSON. So a few things you might instead consider:
1. You could use https://github.com/bufbuild/connect-es to create gRPC-web clients that support JSON and then also use an `encoding.Codec` in your server that supports JSON (if you are using a Go server anyway). The [`Codec`](https://pkg.go.dev/google.golang.org/grpc/encoding#Codec) interface is easy to implement for JSON: the two methods map to functions of the same name in the [`protojson`](https://pkg.go.dev/google.golang.org/protobuf/encoding/protojson) package.
2. You could use [Connect](https://connect.build/) instead of gRPC. It supports JSON out of the box. (Implementations currently available in TS/JS, Go, Kotlin/Android, and Swift/iOS).

**Comment by idc77** [comment]
I'm just looking for a way to consume the grpc server on a web frontend.
Idk what buf has to do with any of this. Everywhere I go in the grpc world I'm met with buf marketing.
Forget I asked, it was a stupid idea.
grpc is not fit for the web.
