### ISSUE TITLE
change the way assets are baked in: go-bindata previously used by go:generate directives no longer available

### ISSUE THREAD

**Issue by fnchooft** [fullstorydev/grpcui#37]
Great project!!

Trying to alter some javascript, but it seems i need go-bindata for this.

Is go-bindata still working for this project?
Since i am not a go-expert i am a bit stuck on this for now.
Some GO-expert might add a section in the README on how to re-compile the assets?

Kind regards,

Using latest go version go1.12.5 linux/amd64 on ubuntu 18.04.2

**Comment by rokostik** [comment]
I'm having similar issues, seems like the current versions of `go-bindata` that I found don't accept the same flags and produce a totally different output.

Could anyone point out the actual `go-bindata` that was used in this project?

**Comment by jhump** [comment]
@fnchooft, sorry I never replied. Something must have been wonky w/ my email notifications, because I never saw your original post.

@rokostik, looks like the version of `go-bindata` I used is no longer available on GitHub. It was SHA 4bf44a02f12e6d3506dd4f79bd4d5555ea77c2d1 from `github.com/jteeuwen/go-bindata`. I know this because I still have this tool locally, as well as details of the commit. So I can re-generate stuff in this repo on my machine.

So this will take a change to update this repo to use a properly supported tool, so that contributions can also re-generate.

Happy to accept a patch.

**Comment by jhump** [comment]
Resolved by #49
