### ISSUE TITLE
"module google.golang.org/grpc@latest found (v1.32.0), but does not contain package google.golang.org/grpc/xds/experimental"

### ISSUE THREAD

**Issue by cannibal-kush** [fullstorydev/grpcui#89]
As the title says, upon trying to go `get github.com/fullstorydev/grpcui/...`

I am greeted with the following output

```go: downloading golang.org/x/crypto v0.0.0-20200622213623-75b288015ac9
go: downloading github.com/pkg/browser v0.0.0-20180916011732-0a3d74bf9ce4
go: finding module for package google.golang.org/grpc/xds/experimental
go: finding module for package google.golang.org/grpc/xds/experimental
C:\Users\[username]\go\pkg\mod\github.com\fullstorydev\grpcurl@v1.6.0\grpcurl.go:35:2: module google.golang.org/grpc@latest found (v1.32.0), but does not contain package google.golang.org/grpc/xds/experimental
```
I've no clue really what this error means, can anyone point me in the right direction?

**Comment by jhump** [comment]
@cannibal-kush, sorry about that. This is fixed in #81, but that hasn't been included in a release yet.

You can either use the latest-unreleased grpcui:

```
go get github.com/fullstorydev/grpcui/...@master
```

_OR_ update to a newer grpcurl, but keep that version of grpcui:

```
go get github.com/fullstorydev/grpcurl/...@v1.7.0
```

**Comment by jhump** [comment]
FYI, the issue is that the grpc-go project _removed_ a package with v1.31. And, until v1.6.1, the grpcurl project depended on it; and grpcui depends on grpcurl. So your modules ended up trying to mix that older version of grpcurl (referenced by grpcui), but then it would not compile with newer version of grpc.

I hope that makes sense.

BTW, another way to fix would be to downgrade the grpc library, back to when that package did exist (instead of using `@latest`):
```
go get google.golang.org/grpc@v1.30.0
```

**Comment by cannibal-kush** [comment]
Thanks for the detailed response. I ended up just using the lower version of grpc. I guess I'll close this issue!
