### ISSUE TITLE
master not tagged

### ISSUE THREAD

**Issue by mhatch-sc** [fullstorydev/grpcui#92]
Any reason master has changes that aren't reflected in the latest tag? Go mod is fetching v1.0.0, but underlying changes in the import chain (grpcui -> grpcurl -> grpc-go) have breaking changes.

```
github.com/fullstorydev/grpcui/standalone imports
        github.com/fullstorydev/grpcui imports
        github.com/fullstorydev/grpcurl imports
        google.golang.org/grpc/xds/experimental: module google.golang.org/grpc@latest (v1.33.0) found, but does not contain package google.golang.org/grpc/xds/experimental
```

It looks like v1.0.0 depends on v1.6.0 of grpcurl, which has this line (https://github.com/fullstorydev/grpcurl/blob/v1.6.0/grpcurl.go#L35). You fixed it starting in v1.6.1, but no tagged version of this library has the fix.

**Comment by jhump** [comment]
> Any reason master has changes that aren't reflected in the latest tag?

We just haven't gotten to a release yet. One of the to-date unreleased things was a new feature that needed some soak/testing time. I think it's ready to go now after a somewhat recent fix and a very recent update to look'n'feel/css. So we'll be making a release soon.

I am very aware of the compatibility issue. See #89. This will indeed be fixed with the next release, which should be this week.

**Comment by jhump** [comment]
Version 1.1.0 was just released.

**Comment by mhatch-sc** [comment]
I assume it was the case that you were planning on it, but not yet done so. Just making sure it wasn't some other reason, like an accidental merge to master or just some automated tagging bot didn't tag the release. Glad to know you're aware of the issue and have the fix prepared. 👍
