### ISSUE TITLE
Support for collections

### ISSUE THREAD

**Issue by cosmin-mogos** [fullstorydev/grpcui#94]
Is there a plan to add collections, similar to what postman has?

**Comment by jhump** [comment]
@cosmin-mogos, nothing along those lines is planned.

**Comment by cosmin-mogos** [comment]
Thank you for your quick reply. We're planning to add grpcui as a library to our service, could we abuse the history functionality to inject some examples?

**Comment by jhump** [comment]
Probably. While I don't think it's widely used (possibly completely _unused_?), the Go packages offer a lot of ways to customize the web UI. You could definitely inject a JS asset that could initialize local storage history with examples or something similar.

You could also bolt this on in a separate page, though that would be much harder right now without #22, since you would also need to add custom code somewhere that could handle something like deep-linking -- so your own page that provides the view of collections and a way to link over to the main gRPC form with the form pre-populated with whatever was selected...

That being said, though there is a lot that _can_ be done, I do understand that a lot of these things are not easy with the current layout of code and APIs in this repo. So if you have any patches that could provide more or easier pluggability/extensibility (without breaking backwards compatibility), they would likely be quite welcome.

**Comment by cosmin-mogos** [comment]
I took a stab at implementing basic support for collections, please have a look at this PR https://github.com/fullstorydev/grpcui/pull/95/files 

The idea is that we can inject a collection with `standalone.ServeAsset("history.json", data)`. This helps developers as they don't have to create complex queries.

The PR also adds a save button to history to make the creation process as easy as possible.
